---
title: "Simple Performance Analysis of Multitransfer Experiments"
output: 
  html_document:
    code_folding: show
---

```{r setup, include=FALSE}
library(tidyverse)
data_path <- "../output"
```

```{r}
NETWORK_ORDER <- c(
  'none',
  'wired',
  'wired-lossy',
  'hi-delay-jittery',
  'hi-delay-jittery-lossy'
)
```

```{r}
transfers <- read_csv(
  list.files(data_path, pattern = "*.csv", full.names = TRUE)
) |>
  mutate(
    wallclock = as.numeric(wallclock),
    concurrent = factor(concurrent, levels = sort(unique(concurrent))),
    emulator = factor(emulator, levels = NETWORK_ORDER)
  ) |>
  filter(!is.na(wallclock))
```

```{r}
means <- transfers |> 
  group_by(netsize, concurrent, strategy, emulator) |>
  summarise(wallclock = median(wallclock, na.rm = TRUE), .groups = "drop")
means
```

```{r}
options(ark.plot.width = 10)
options(ark.plot.height = 6)

ggplot(transfers, 
  aes(x = concurrent, y = wallclock, group = strategy)) + 
  geom_line(data = means, lwd = 1, col = 'orange', lty = 2) +
  geom_point( col = scales::alpha("black", 0.1)) + 
  facet_wrap(strategy ~ netsize, labeller = labeller(
    strategy = function(x) paste0("Delay strategy: **", x, "**"),
    netsize = function(x) paste0("Network size: **", x, "**")
  )) +
  ylab("transfer time (s)") +
  xlab("concurrent transfers") +
  theme_minimal() + 
  theme(
    strip.text = ggtext::element_markdown()
  )
```


```{r}
options(ark.plot.width = 10)
options(ark.plot.height = 6)

ggplot(transfers, 
  aes(x = emulator, y = wallclock, group = emulator, fill = emulator)) + 
  geom_point(col = scales::alpha("black", 0.1)) + 
  geom_violin() +
  facet_wrap(strategy ~ netsize, labeller = labeller(
    strategy = function(x) paste0("Delay strategy: **", x, "**"),
    netsize = function(x) paste0("Network size: **", x, "**")
  )) +
  ylab("transfer time (s)") +
  xlab("") + 
  theme_minimal() +
  guides(fill = "none") + 
  theme(
    strip.text = ggtext::element_markdown()
  )
```


```{r}
means
```